include:
  - board: nice_nano@2.0.0//zmk
    shield: felix_left
    artifact-name: felix_left
  - board: nice_nano@2.0.0//zmk
    shield: felix_right
    artifact-name: felix_right
  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
    artifact-name: settings_reset
